using UnityEngine;
using System.Collections;

public class enemyShotMovement : MonoBehaviour {

    public float enemyShotVelocity;
    public Rigidbody rb;
    public float lifeDuration;
    private Attractor Core;
    public float Xpos;
    public float Ypos;
    public float radius;
    // Use this for initialization
    void Start()
    {
        rb = GetComponent<Rigidbody>();
        rb.velocity = transform.TransformDirection(new Vector3(-enemyShotVelocity, 0, 0));
    }

    // Update is called once per frame
    void Update()
    {
        Vector3 Xpointer = (Core.transform.position - transform.position).normalized;
        Xpointer.z = 0;
        float temp = Xpointer.x;
        Xpointer.x = -Xpointer.y;
        Xpointer.y = temp;

        transform.position = transform.position + ((Xpointer * -1) / 5);

        StartCoroutine("Destroybullet");
    }
    public IEnumerator Destroybullet()
    {
        yield return new WaitForSeconds(lifeDuration);
        Destroy(gameObject);
    }

        }
